# Generated by Django 2.2.6 on 2020-04-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetails',
            name='createdBy',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
