# Generated by Django 2.2.6 on 2020-04-08 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogBookEntry',
            fields=[
                ('SerialNumber', models.AutoField(primary_key=True, serialize=False)),
                ('CreatedAt', models.DateField(default=django.utils.timezone.now)),
                ('Author', models.TextField(max_length=30)),
                ('Designation', models.TextField(max_length=30)),
                ('Subject', models.TextField(max_length=300)),
                ('ReportedTo', models.TextField(max_length=30)),
                ('InstructedBy', models.TextField(max_length=30)),
            ],
        ),
    ]
