Vagrant.configure(2) do |config|
    config.vm.hostname= "SampleTest"
    config.vm.box  = "ubuntu/trusty64"
    config.vm.network "private_network", ip: "192.168.56.100"
    config.vm.network :forwarded_port, guest:80, host:8700
    config.vm.provider 'Virtualbox' do |vb|
        vb.gui = false
        vb.memory = "1024"
        vb.cpus = "2"
    end
end
