# Generated by Django 2.2.6 on 2020-04-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlLists',
            fields=[
                ('SerialNumber', models.AutoField(primary_key=True, serialize=False)),
                ('internalIP', models.TextField(max_length=30)),
                ('externalIP', models.TextField(max_length=30)),
                ('appName', models.TextField(max_length=100)),
                ('appURL', models.TextField(max_length=200)),
                ('Dept', models.TextField(max_length=200)),
            ],
        ),
    ]
